### ISSUE TITLE
[tracking]

### ISSUE THREAD

**Issue by Haroenv** [Haroenv/algolia-technical-test#1]
- [x] MVC
- [x] algolia post adds
- [x] algolia delete deletes
- [x] search
- [x] pagination
- [x] faceting
- [x] sort by rank (algolia slaves)
- [x] components used for frontend
  - [x] divide in components
  - [x] components in separate files
- [x] looks good
- [x] document the structure
- [x] deploy on Heroku

**Comment by vvo** [comment]
There may be a leftover in public/js right?

**Comment by Haroenv** [comment]
Oh, you're right, I decided to inline that and it should be deleted

**Comment by Haroenv** [comment]
https://github.com/Haroenv/algolia-technical-test/commit/15bedc5d6a8ee1050d9c7223ea5732d15420633b fixed that
